apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    {{- include "annotations" . | indent 2 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
      {{- include "podAnnotations" . | indent 6 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          command: ["/go-hello-world"]
          {{- if .Values.args }}
          args:
          {{- range $arg := .Values.args }}
            - "{{ $arg }}"
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 3

            {{- if .Values.env }}
            env:
            {{- range $env := .Values.env }}
              - name: {{ $env.key }}
                value: {{ $env.value }}
            {{- end }}
            {{- end }}
