# Default values for go-hello-world-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: "1"

image:
  repository: ghcr.io/wasilak/go-hello-world
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  name: go-hello-world
  type: ClusterIP
  port: 5000
  targetPort: 5000

imagePullPolicy: Always

args:
  - "-listen-addr=:5000"
  - "-log-format=json"
  - "-log-level=info"
  # - "-otel-enabled"

env:
  []
  # - name: "OTEL_SERVICE_NAME"
  #   value: "go-hello-world"
  # - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
  #   value: ""
