# Default values for go-hello-world-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: "1"

image:
  repository: quay.io/wasilak/go-hello-world
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  name: go-hello-world
  type: ClusterIP
  port: 5000
  targetPort: 5000

imagePullPolicy: Always
